
---
#로컬
spring:
  config:
    activate:
      on-profile: local

#
server:
  port: 8081
  servlet:
    session:
      timeout: 30s # 30초
      cookie:
        http-only: false
        secure: false
        same-site: LAX
